import type { BlogPost } from "./types/blog";

export const seedBlogPosts: BlogPost[] = [
    {
        slug: "hello-world",
        title: "Hello World",
        excerpt: "这是第一篇示例文章，用来预览博客列表和详情页的样式效果。",
        date: "2026-07-28",
        tags: ["随笔"],
        content: "# Hello World\n\n这是一篇示例文章，用来预览博客详情页的排版效果。\n\n> 简洁、克制、留白。\n\n希望你喜欢这个新设计。",
        published: true,
    },
    {
        slug: "design-notes",
        title: "一些设计笔记",
        excerpt: "关于个人网站的设计思路：少即是多，保持克制，让内容自己说话。",
        date: "2026-07-15",
        tags: ["设计", "思考"],
        content: "# 一些设计笔记\n\n设计个人网站时，最重要的是不要过度设计。\n\n- 留白很重要\n- 字体和字号要有层次\n- 颜色尽量克制\n\n让内容自己说话。",
        published: true,
    },
    {
        slug: "travel-in-summer",
        title: "夏日旅行随想",
        excerpt: "记录一次短暂的夏日旅行，海边的风、街道的光影，还有那些不期而遇的瞬间。",
        date: "2026-06-30",
        tags: ["旅行", "摄影"],
        content: "# 夏日旅行随想\n\n夏天的海，总是让人忍不住多待一会儿。\n\n![placeholder](https://picsum.photos/800/450)\n\n海风、阳光、街道，一切都刚刚好。",
        published: true,
    },
    {
        slug: "weekly-review-01",
        title: "周报 #1：重新开始写东西",
        excerpt: "记录这周的工作、阅读与思考。重新捡起写作这件事，比想象中更难。",
        date: "2026-06-22",
        tags: ["周报", "思考"],
        content: "# 周报 #1\n\n这周重新开始写东西，发现坚持比开始更难。\n\n## 阅读\n\n读了几篇关于极简设计的文章。\n\n## 思考\n\n少即是多，但少也需要勇气。",
        published: true,
    },
    {
        slug: "camera-and-memory",
        title: "相机与记忆",
        excerpt: "拍照是为了记住，还是为了忘记？一些关于摄影的随想。",
        date: "2026-06-10",
        tags: ["摄影", "随笔"],
        content: "# 相机与记忆\n\n每次按下快门，都是在和某个瞬间做交易。\n\n> 我们记得的，也许只是照片里的那个版本。",
        published: true,
    },
    {
        slug: "build-personal-site",
        title: "搭建这个网站的记录",
        excerpt: "从选型到部署，记录个人网站的搭建过程，以及一些踩过的坑。",
        date: "2026-05-28",
        tags: ["技术", "设计"],
        content: "# 搭建这个网站的记录\n\n用 Next.js + Tailwind CSS + Supabase 搭建了这个网站。\n\n```tsx\nexport default function Home() {\n  return <main>Hello World</main>;\n}\n```\n\n过程比想象中顺利。",
        published: true,
    },
    {
        slug: "city-walk-shanghai",
        title: "上海 City Walk",
        excerpt: "周末在老城区走了两万步，梧桐树、老洋房、咖啡馆，构成了这座城市的另一种节奏。",
        date: "2026-05-15",
        tags: ["旅行", "城市"],
        content: "# 上海 City Walk\n\n两万步，从法租界走到外滩。\n\n![placeholder](https://picsum.photos/800/450)\n\n这座城市最适合用脚步丈量。",
        published: true,
    },
    {
        slug: "year-end-2025",
        title: "2025 年末随想",
        excerpt: "回顾这一年，经历了许多变化，也有一些新的期待。",
        date: "2025-12-20",
        tags: ["随笔"],
        content: "# 2025 年末随想\n\n这一年发生了很多事。\n\n> 成长总是伴随着不确定。",
        published: true,
    },
    {
        slug: "autumn-reading",
        title: "秋日书单",
        excerpt: "最近读的几本书，以及一些零散的感想。",
        date: "2025-10-08",
        tags: ["阅读", "思考"],
        content: "# 秋日书单\n\n- 《设计心理学》\n- 《重来》\n- 《禅与摩托车维修艺术》\n\n每一本都让我重新思考一些事情。",
        published: true,
    },
];
